services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  eureka-server:
    image: usmanr45/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-net

  api-gateway:
    image: usmanr45/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - order-service
      - product-service
    networks:
      - ecommerce-net

  order-service:
    image: usmanr45/order-service:latest
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - ecommerce-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orderdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_APPLICATION_NAME: order-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SERVER_PORT: 8081

  product-service:
    image: yaragal/productservice_ah_t5:latest
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server
    networks:
      - ecommerce-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_APPLICATION_NAME: product-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: true
      EUREKA_CLIENT_FETCH-REGISTRY: true
      SERVER_PORT: 8082

volumes:
  mysql_data:
  postgres_data:

networks:
  ecommerce-net:
